name: build-push
on: [workflow_dispatch]
jobs:
  test:
    runs-on: nscloud
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v6
    strategy:
      matrix:
        a: [1, 2, 3, 4]
        b: [1, 2, 3, 4]
